library(fUnitRoots)

#Stationnarisation des variables

  #MSE
  adf.test(MSEAnn)
  MSEAnnSta <- diff(MSEAnn, differences = 2)
  acf(MSEAnnSta)
  pacf(MSEAnnSta)
  kpss.test(MSEAnnSta)
  plot(MSEAnnSta)
  MSEAnnTrain <- window(MSEAnn, end=2015)
  MSEAnnTest <- window(MSEAnn, start=2016)
  
  adf.test(MSETrim)
  MSETrimSta <- diff(MSETrim, differences = 2, lag = 4)
  acf(MSETrimSta, lag=20)
  pacf(MSETrimSta)
  kpss.test(MSETrimSta)
  plot(MSETrimSta)
  MSEAnnTrain <- window(MSEAnn, end=c(2015,4))
  MSEAnnTest <- window(MSEAnn, start=2016)

  #PIB
  summary(lm(MSEAnn ~ PIBAnn[1:28]))
  adf.test(PIBAnn)
  PIBAnnSta <- diff(PIBAnn, differences = 1)
  acf(PIBAnnSta)
  pacf(PIBAnnSta)
  kpss.test(PIBAnnSta)
  plot(PIBAnnSta)
  PIBAnnTrain <- window(PIBAnn, end=2015)
  PIBAnnTest <- window(PIBAnn, start=2016)
  
  summary(lm(MSETrim ~ PIBTrim))
  adf.test(PIBTrim)
  PIBTrimSta <- diff(PIBTrim, differences = 1)
  acf(PIBTrimSta)
  pacf(PIBTrimSta)
  kpss.test(PIBTrimSta)
  adfTest(PIBTrimSta, type='c')
  plot(PIBTrimSta)
  PIBAnnTrain <- window(PIBAnn, end=c(2015,4))
  PIBAnnTest <- window(PIBAnn, start=2016)
  
  #SMIC
  summary(lm(MSEAnn ~ SMICAnn[1:28]))
  adf.test(SMICAnn)
  SMICAnnSta <- diff(SMICAnn, differences = 2)
  acf(SMICAnnSta)
  pacf(SMICAnnSta)
  kpss.test(SMICAnnSta)
  plot(SMICAnnSta)
  SMICAnnTrain <- window(SMICAnn, end=2015)
  SMICAnnTest <- window(SMICAnn, start=2016)
  
  summary(lm(MSETrim ~ SMICTrim[1:109]))
  adf.test(SMICTrim[1:109])
  SMICTrimSta <- diff(SMICTrim, differences = 1, lag = 4)
  acf(SMICTrimSta)
  pacf(SMICTrimSta)
  kpss.test(SMICTrimSta)
  plot(SMICTrimSta)
  SMICAnnTrain <- window(SMICAnn, end=c(2015,4))
  SMICAnnTest <- window(SMICAnn, start=2016)
  
  #TCHO
  summary(lm(MSEAnn ~ TCHOAnn[1:28]))
  adf.test(TCHOAnn)
  TCHOAnnSta <- diff(TCHOAnn, differences = 1)
  acf(TCHOAnnSta)
  pacf(TCHOAnnSta)
  kpss.test(TCHOAnnSta)
  plot(TCHOAnnSta)
  TCHOAnnTrain <- window(TCHOAnn, end=2015)
  TCHOAnnTest <- window(TCHOAnn, start=2016)
  
  summary(lm(MSETrim ~ TCHOTrim[1:109]))
  adf.test(TCHOTrim)
  TCHOTrimSta <- diff(TCHOTrim, differences = 1)
  acf(TCHOTrimSta)
  pacf(TCHOTrimSta)
  kpss.test(TCHOTrimSta)
  plot(TCHOTrimSta)
  TCHOAnnTrain <- window(TCHOAnn, end=c(2015,4))
  TCHOAnnTest <- window(TCHOAnn, start=2016)
  
  #AGED
  summary(lm(MSEAnn ~ AGEDAnn[1:28]))
  adf.test(AGEDAnn)
  AGEDAnnSta <- diff(AGEDAnn, differences = 1)
  acf(AGEDAnnSta)
  pacf(AGEDAnnSta)
  kpss.test(AGEDAnnSta)
  plot(AGEDAnnSta)
  AGEDAnnTrain <- window(AGEDAnn, end=2015)
  AGEDAnnTest <- window(AGEDAnn, start=2016)
  
  