library(fUnitRoots)

#Stationnarisation des variables

  #MSE
  adf.test(MSEAnn)
  MSEAnnSta <- diff(MSEAnn, differences = 2)
  acf(MSEAnnSta)
  pacf(MSEAnnSta)
  kpss.test(MSEAnnSta)
  plot(MSEAnnSta)
  MSEAnnTrain <- window(MSEAnnSta, end=2015)
  MSEAnnTest <- window(MSEAnnSta, start=2016)
  
  adf.test(MSETrim)
  MSETrimSta <- diff(MSETrim, differences = 2, lag = 4)
  acf(MSETrimSta, lag=20)
  pacf(MSETrimSta)
  kpss.test(MSETrimSta)
  plot(MSETrimSta)
  MSETrimTrain <- window(MSETrimSta, end=c(2015,4))
  MSETrimTest <- window(MSETrimSta, start=2016)

  #PIB
  summary(lm(MSEAnn ~ PIBAnn[1:28]))
  adf.test(PIBAnn)
  PIBAnnSta <- diff(PIBAnn, differences = 1)
  acf(PIBAnnSta)
  pacf(PIBAnnSta)
  kpss.test(PIBAnnSta)
  plot(PIBAnnSta)
  PIBAnnTrain <- window(PIBAnnSta, start = 1992, end=2015)
  PIBAnnTest <- window(PIBAnnSta, start=2016)
  
  summary(lm(MSETrim[1:109] ~ PIBTrim))
  adf.test(PIBTrim)
  PIBTrimSta <- diff(PIBTrim, differences = 1)
  acf(PIBTrimSta)
  pacf(PIBTrimSta)
  kpss.test(PIBTrimSta)
  adfTest(PIBTrimSta, type='c')
  plot(PIBTrimSta)
  PIBTrimTrain <- window(PIBTrimSta, start = 1992, end=c(2015,4))
  PIBTrimTest <- window(PIBTrimSta, start=2016)
  
  #SMIC
  summary(lm(MSEAnn ~ SMICAnn[1:28]))
  adf.test(SMICAnn)
  SMICAnnSta <- diff(SMICAnn, differences = 2)
  acf(SMICAnnSta)
  pacf(SMICAnnSta)
  kpss.test(SMICAnnSta)
  plot(SMICAnnSta)
  SMICAnnTrain <- window(SMICAnnSta, start = 1992, end=2015)
  SMICAnnTest <- window(SMICAnnSta, start=2016)
  
  summary(lm(MSETrim ~ SMICTrim[1:110]))
  adf.test(SMICTrim[1:110])
  SMICTrimSta <- diff(SMICTrim, differences = 1, lag = 4)
  acf(SMICTrimSta)
  pacf(SMICTrimSta)
  kpss.test(SMICTrimSta)
  plot(SMICTrimSta)
  SMICTrimTrain <- window(SMICTrimSta, start = 1992, end=c(2015,4))
  SMICTrimTest <- window(SMICTrimSta, start=2016)
  
  #TCHO
  summary(lm(MSEAnn ~ TCHOAnn[1:28]))
  adf.test(TCHOAnn)
  TCHOAnnSta <- diff(TCHOAnn, differences = 1)
  acf(TCHOAnnSta)
  pacf(TCHOAnnSta)
  kpss.test(TCHOAnnSta)
  plot(TCHOAnnSta)
  TCHOAnnTrain <- window(TCHOAnnSta, start = 1992, end=2015)
  TCHOAnnTest <- window(TCHOAnnSta, start=2016)
  
  summary(lm(MSETrim ~ TCHOTrim[1:110]))
  adf.test(TCHOTrim[1:110])
  TCHOTrimSta <- diff(TCHOTrim, differences = 1)
  acf(TCHOTrimSta)
  pacf(TCHOTrimSta)
  kpss.test(TCHOTrimSta)
  plot(TCHOTrimSta)
  TCHOTrimTrain <- window(TCHOTrimSta, start = 1992, end=c(2015,4))
  TCHOTrimTest <- window(TCHOTrimSta, start=2016)
  
  #AGED
  summary(lm(MSEAnn ~ AGEDAnn[1:28]))
  adf.test(AGEDAnn)
  AGEDAnnSta <- diff(AGEDAnn, differences = 1)
  acf(AGEDAnnSta)
  pacf(AGEDAnnSta)
  kpss.test(AGEDAnnSta)
  plot(AGEDAnnSta)
  AGEDAnnTrain <- window(AGEDAnnSta, start = 1992, end=2015)
  AGEDAnnTest <- window(AGEDAnnSta, start=2016)
  
  