library(fUnitRoots)

#Stationnarisation des variables

  #MSE
  adf.test(MSEAnn)
  MSEAnnSta <- diff(MSEAnn, differences = 2)
  acf(MSEAnnSta)
  pacf(MSEAnnSta)
  kpss.test(MSEAnnSta)
  plot(MSEAnnSta)
  MSEAnnStaTrain <- window(MSEAnnSta, end=2015)
  MSEAnnStaTest <- window(MSEAnnSta, start=2016)
  
  adf.test(MSETrim)
  MSETrimSta <- na.omit(decompose(MSETrim, "multiplicative")$random)
  #MSETrimSta <- diff(MSETrim, differences = 2, lag = 4)
  acf(MSETrimSta)
  pacf(MSETrimSta)
  kpss.test(MSETrimSta)
  plot(MSETrimSta)
  MSETrimStaTrain <- window(MSETrimSta, end=c(2015,4))
  MSETrimStaTest <- window(MSETrimSta, start=2016)

  #PIB
  summary(lm(MSEAnn ~ PIBAnn[1:28]))
  adf.test(PIBAnn)
  PIBAnnSta <- diff(PIBAnn, differences = 1)
  acf(PIBAnnSta)
  pacf(PIBAnnSta)
  kpss.test(PIBAnnSta)
  plot(PIBAnnSta)
  PIBAnnStaTrain <- window(PIBAnnSta, start = 1992, end=2015)
  PIBAnnStaTest <- window(PIBAnnSta, start=2016)
  
  summary(lm(MSETrim[1:109] ~ PIBTrim))
  adf.test(PIBTrim)
  PIBTrimSta <- na.omit(decompose(PIBTrim, "multiplicative")$random)
  acf(PIBTrimSta)
  pacf(PIBTrimSta)
  kpss.test(PIBTrimSta)
  adfTest(PIBTrimSta, type='c')
  plot(PIBTrimSta)
  PIBTrimStaTrain <- window(PIBTrimSta, end=c(2015,4))
  PIBTrimStaTest <- window(PIBTrimSta, start=2016)
  
  #SMIC
  summary(lm(MSEAnn ~ SMICAnn[1:28]))
  adf.test(SMICAnn)
  SMICAnnSta <- diff(SMICAnn, differences = 2)
  acf(SMICAnnSta)
  pacf(SMICAnnSta)
  kpss.test(SMICAnnSta)
  plot(SMICAnnSta)
  SMICAnnStaTrain <- window(SMICAnnSta, start = 1992, end=2015)
  SMICAnnStaTest <- window(SMICAnnSta, start=2016)
  
  summary(lm(MSETrim ~ SMICTrim[1:110]))
  adf.test(SMICTrim[1:110])
  SMICTrimSta <- na.omit(decompose(SMICTrim)$random)
  acf(SMICTrimSta)
  pacf(SMICTrimSta)
  kpss.test(SMICTrimSta)
  plot(SMICTrimSta)
  SMICTrimStaTrain <- window(SMICTrimSta, end=c(2015,4))
  SMICTrimTest <- window(SMICTrimSta, start=2016)
  
  #TCHO
  summary(lm(MSEAnn ~ TCHOAnn[1:28]))
  adf.test(TCHOAnn)
  TCHOAnnSta <- diff(TCHOAnn, differences = 1)
  acf(TCHOAnnSta)
  pacf(TCHOAnnSta)
  kpss.test(TCHOAnnSta)
  plot(TCHOAnnSta)
  TCHOAnnStaTrain <- window(TCHOAnnSta, start = 1992, end=2015)
  TCHOAnnStaTest <- window(TCHOAnnSta, start=2016)
  
  summary(lm(MSETrim ~ TCHOTrim[1:110]))
  adf.test(TCHOTrim[1:110])
  TCHOTrimSta <- na.omit(decompose(TCHOTrim)$random)
  acf(TCHOTrimSta)
  pacf(TCHOTrimSta)
  kpss.test(TCHOTrimSta)
  plot(TCHOTrimSta)
  TCHOTrimStaTrain <- window(TCHOTrimSta, end=c(2015,4))
  TCHOTrimStaTest <- window(TCHOTrimSta, start=2016)
  
  #AGED
  summary(lm(MSEAnn ~ AGEDAnn[1:28]))
  adf.test(AGEDAnn)
  AGEDAnnSta <- diff(AGEDAnn, differences = 1)
  acf(AGEDAnnSta)
  pacf(AGEDAnnSta)
  kpss.test(AGEDAnnSta)
  plot(AGEDAnnSta)
  AGEDAnnStaTrain <- window(AGEDAnnSta, start = 1992, end=2015)
  AGEDAnnStaTest <- window(AGEDAnnSta, start=2016)
  
  