#Ce script correspond à la mise en place de modèles VARMA

library(MASS)
library(vars)

###Modèles VAR
##Annuel
#1 Variable auxiliaire

#AGED
VAR(cbind(MSEAnnTrain, AGEDAnnTrain), p=5, type="trend")
VARAGED <- forecast(VAR(cbind(MSEAnnTrain, AGEDAnnTrain), p=5))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARAGED$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARAGED$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(AGEDAnnTest, ylim=c(200,300))
lines(VARAGED$forecast$AGEDAnnTrain$mean, col = "red")

#PIB
VARselect(cbind(MSEAnnTrain, PIBAnnTrain), lag.max = 6)
VAR(cbind(MSEAnnTrain, PIBAnnTrain), p=6, type="trend")
VARPIB <- forecast(VAR(cbind(MSEAnnTrain, PIBAnnTrain), p=6))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARPIB$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARPIB$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(PIBAnnTest, ylim=c(2000,2300))
lines(VARPIB$forecast$PIBAnnTrain$mean, col = "red")

#SMIC
VARselect(cbind(MSEAnnTrain, SMICAnnTrain), lag.max = 6)
VAR(cbind(MSEAnnTrain, SMICAnnTrain), p=6, type="trend")
VARSMIC <- forecast(VAR(cbind(MSEAnnTrain, SMICAnnTrain), p=6))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARSMIC$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARSMIC$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(SMICAnnTest, ylim=c(9,11))
lines(VARSMIC$forecast$SMICAnnTrain$mean, col = "red")

#TCHO
VARselect(cbind(MSEAnnTrain, TCHOAnnTrain), lag.max = 6)
VAR(cbind(MSEAnnTrain, TCHOAnnTrain), p=6, type="trend")
VARTCHO <- forecast(VAR(cbind(MSEAnnTrain, TCHOAnnTrain), p=6))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARTCHO$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARTCHO$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(TCHOAnnTest, ylim=c(8,10))
lines(VARTCHO$forecast$TCHOAnnTrain$mean, col = "red")

plot(MSEAnnTest, main="Comparaison des modèles avec 1 variable", ylim=c(5e+09,6e+09))
lines(VARAGED$forecast$MSEAnnTrain$mean, col="blue")
lines(VARPIB$forecast$MSEAnnTrain$mean, col="green")
lines(VARSMIC$forecast$MSEAnnTrain$mean, col="red")
lines(VARTCHO$forecast$MSEAnnTrain$mean, col="gold")
legend('bottomleft', legend = c('Série MSE', 'Aged', 'PIB', 'SMIC', 'Taux chômage'),
       col=c('black', 'blue', 'green', 'red', 'gold'), lty=1, cex=0.8)

#2 Variables

#Aged & PIB
VARselect(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain), lag.max=5, type="trend")
VAR(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain), p=5, type="trend")
VARAGEDPIB <- forecast(VAR(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain), p=5))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARAGEDPIB$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARAGEDPIB$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(AGEDAnnTest, ylim=c(-60,300))
lines(VARAGEDPIB$forecast$AGEDAnnTrain$mean, col = "red")
plot(PIBAnnTest, ylim=c(2000,3000))
lines(VARAGEDPIB$forecast$PIBAnnTrain$mean, col = "red")

#Aged & SMIC
VARselect(cbind(MSEAnnTrain, AGEDAnnTrain, SMICAnnTrain), lag.max=4, type="trend")
VAR(cbind(MSEAnnTrain, AGEDAnnTrain, SMICAnnTrain), p=4, type="trend")
VARAGEDSMIC <- forecast(VAR(cbind(MSEAnnTrain, AGEDAnnTrain, SMICAnnTrain), p=4))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARAGEDSMIC$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARAGEDSMIC$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(AGEDAnnTest, ylim=c(-60,300))
lines(VARAGEDSMIC$forecast$AGEDAnnTrain$mean, col = "red")
plot(SMICAnnTest, ylim=c(2000,3000))
lines(VARAGEDSMIC$forecast$SMICAnnTrain$mean, col = "red")

#Aged & TCHO
VARselect(cbind(MSEAnnTrain, AGEDAnnTrain, TCHOAnnTrain), lag.max=4, type="trend")
VAR(cbind(MSEAnnTrain, AGEDAnnTrain, TCHOAnnTrain), p=4, type="trend")
VARAGEDTCHO <- forecast(VAR(cbind(MSEAnnTrain, AGEDAnnTrain, TCHOAnnTrain), p=4))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARAGEDTCHO$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARAGEDTCHO$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(AGEDAnnTest, ylim=c(-60,300))
lines(VARAGEDTCHO$forecast$AGEDAnnTrain$mean, col = "red")
plot(TCHOAnnTest, ylim=c(8.5,10))
lines(VARAGEDTCHO$forecast$TCHOAnnTrain$mean, col = "red")

#PIB & SMIC
VARselect(cbind(MSEAnnTrain, PIBAnnTrain, SMICAnnTrain), lag.max=4, type="trend")
VAR(cbind(MSEAnnTrain, PIBAnnTrain, SMICAnnTrain), p=4, type="trend")
VARPIBSMIC <- forecast(VAR(cbind(MSEAnnTrain, PIBAnnTrain, SMICAnnTrain), p=4, type="trend"))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARPIBSMIC$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARPIBSMIC$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(PIBAnnTest, ylim=c(1900,2300))
lines(VARPIBSMIC$forecast$PIBAnnTrain$mean, col = "red")
plot(SMICAnnTest, ylim=c(9.5,10.5))
lines(VARPIBSMIC$forecast$SMICAnnTrain$mean, col = "red")

#PIB & TCHO
VARselect(cbind(MSEAnnTrain, PIBAnnTrain, TCHOAnnTrain), lag.max=4, type="trend")
VAR(cbind(MSEAnnTrain, PIBAnnTrain, TCHOAnnTrain), p=4, type="trend")
VARPIBTCHO <- forecast(VAR(cbind(MSEAnnTrain, PIBAnnTrain, TCHOAnnTrain), p=4, type="trend"))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARPIBTCHO$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARPIBTCHO$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(PIBAnnTest, ylim=c(1900,2300))
lines(VARPIBTCHO$forecast$PIBAnnTrain$mean, col = "red")
plot(TCHOAnnTest, ylim=c(8.5,11))
lines(VARPIBTCHO$forecast$TCHOAnnTrain$mean, col = "red")

#SMIC & TCHO
VARselect(cbind(MSEAnnTrain, SMICAnnTrain, TCHOAnnTrain), lag.max=4, type="trend")
VAR(cbind(MSEAnnTrain, SMICAnnTrain, TCHOAnnTrain), p=1, type="trend")
VARSMICTCHO <- forecast(VAR(cbind(MSEAnnTrain, SMICAnnTrain, TCHOAnnTrain), p=1, type="trend"))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARSMICTCHO$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARSMICTCHO$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(SMICAnnTest, ylim=c(9.5,11))
lines(VARSMICTCHO$forecast$SMICAnnTrain$mean, col = "red")
plot(TCHOAnnTest, ylim=c(8.5,11.5))
lines(VARSMICTCHO$forecast$TCHOAnnTrain$mean, col = "red")

plot(MSEAnnTest, main="Comparaison des modèles avec 2 variables", ylim=c(4.5e+09, 6e+09))
lines(VARAGEDPIB$forecast$MSEAnnTrain$mean, col="red")
lines(VARAGEDSMIC$forecast$MSEAnnTrain$mean, col="blue")
lines(VARAGEDTCHO$forecast$MSEAnnTrain$mean, col="green")
lines(VARPIBSMIC$forecast$MSEAnnTrain$mean, col="gold")
lines(VARPIBTCHO$forecast$MSEAnnTrain$mean, col="purple")
lines(VARSMICTCHO$forecast$MSEAnnTrain$mean, col="brown")
legend('bottomleft', 
       legend = c('Série MSE', 'Aged & PIB', 'Aged & SMIC', 'Aged & Taux chômage',
                  'PIB & SMIC', 'PIB & Taux chômage', 'SMIC & Taux chômage'),
       col=c('black', 'red', 'blue', 'green', 'gold', 'purple', 'brown'), lty=1, cex=0.8)

#3 Variables
#Aged & PIB & SMIC
VARselect(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain, SMICAnnTrain), lag.max=2, type="trend")
VAR(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain, SMICAnnTrain), p=2, type="trend")
VARAGEDPIBSMIC <- forecast(VAR(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain, SMICAnnTrain), p=2, type="trend"))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARAGEDPIBSMIC$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARAGEDPIBSMIC$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(AGEDAnnTest, ylim=c(250,375))
lines(VARAGEDPIBSMIC$forecast$AGEDAnnTrain$mean, col = "red")
plot(PIBAnnTest, ylim=c(2000,2500))
lines(VARAGEDPIBSMIC$forecast$PIBAnnTrain$mean, col = "red")
plot(SMICAnnTest, ylim=c(8.5,11.5))
lines(VARAGEDPIBSMIC$forecast$SMICAnnTrain$mean, col = "red")

#Aged & PIB & TCHO
VARselect(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain, TCHOAnnTrain), lag.max=3, type="trend")
VAR(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain, TCHOAnnTrain), p=3, type="trend")
VARAGEDPIBTCHO <- forecast(VAR(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain, TCHOAnnTrain), p=3, type="trend"))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARAGEDPIBTCHO$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARAGEDPIBTCHO$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(AGEDAnnTest, ylim=c(20,375))
lines(VARAGEDPIBTCHO$forecast$AGEDAnnTrain$mean, col = "red")
plot(PIBAnnTest, ylim=c(2000,2500))
lines(VARAGEDPIBTCHO$forecast$PIBAnnTrain$mean, col = "red")
plot(TCHOAnnTest, ylim=c(5,10))
lines(VARAGEDPIBTCHO$forecast$TCHOAnnTrain$mean, col = "red")

#Aged & SMIC & TCHO
VARselect(cbind(MSEAnnTrain, AGEDAnnTrain, SMICAnnTrain, TCHOAnnTrain), lag.max=3, type="trend")
VAR(cbind(MSEAnnTrain, AGEDAnnTrain, SMICAnnTrain, TCHOAnnTrain), p=3, type="trend")
VARAGEDSMICTCHO <- forecast(VAR(cbind(MSEAnnTrain, AGEDAnnTrain, SMICAnnTrain, TCHOAnnTrain), p=3, type="trend"))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARAGEDSMICTCHO$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARAGEDSMICTCHO$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(AGEDAnnTest, ylim=c(20,375))
lines(VARAGEDSMICTCHO$forecast$AGEDAnnTrain$mean, col = "red")
plot(SMICAnnTest, ylim=c(9,12.5))
lines(VARAGEDSMICTCHO$forecast$SMICAnnTrain$mean, col = "red")
plot(TCHOAnnTest, ylim=c(8.5,11))
lines(VARAGEDSMICTCHO$forecast$TCHOAnnTrain$mean, col = "red")

#PIB & SMIC & TCHO
VARselect(cbind(MSEAnnTrain, PIBAnnTrain, SMICAnnTrain, TCHOAnnTrain), lag.max=2, type="trend")
VAR(cbind(MSEAnnTrain, PIBAnnTrain, SMICAnnTrain, TCHOAnnTrain), p=2, type="trend")
VARPIBSMICTCHO <- forecast(VAR(cbind(MSEAnnTrain, PIBAnnTrain, SMICAnnTrain, TCHOAnnTrain), p=2, type="trend"))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARAGEDSMICTCHO$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARAGEDSMICTCHO$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(PIBAnnTest, ylim=c(2000,2500))
lines(VARAGEDSMICTCHO$forecast$PIBAnnTrain$mean, col = "red")
plot(SMICAnnTest, ylim=c(9,12.5))
lines(VARAGEDSMICTCHO$forecast$SMICAnnTrain$mean, col = "red")
plot(TCHOAnnTest, ylim=c(8.5,11))
lines(VARAGEDSMICTCHO$forecast$TCHOAnnTrain$mean, col = "red")


plot(MSEAnnTest, main="Comparaison des modèles avec 3 variables", ylim=c(5e+09, 5.5e+09))
lines(VARAGEDPIBSMIC$forecast$MSEAnnTrain$mean, col="blue")
lines(VARAGEDPIBTCHO$forecast$MSEAnnTrain$mean, col="green")
lines(VARAGEDSMICTCHO$forecast$MSEAnnTrain$mean, col="red")
lines(VARPIBSMICTCHO$forecast$MSEAnnTrain$mean, col="gold")
legend('bottomright', legend = c('Série MSE', 'Aged & PIB & SMIC', 'Aged & PIB & Taux chômage',
                           'Aged & SMIC & Taux chômage', 'PIB & SMIC & Taux chômage'),
       col=c('black', 'blue', 'green', 'red', 'gold'), lty=1, cex=0.8)

#4 Variables
VARselect(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain, SMICAnnTrain, TCHOAnnTrain), lag.max=2, type="trend")
VAR(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain, SMICAnnTrain, TCHOAnnTrain), p=2, type="trend")
VARCOMPLET <- forecast(VAR(cbind(MSEAnnTrain, AGEDAnnTrain, PIBAnnTrain, SMICAnnTrain, TCHOAnnTrain), p=2, type="trend"))
plot(MSEAnnTest, ylim=c(5e+09, 6e+09))
lines(VARCOMPLET$forecast$MSEAnnTrain$mean, col = "red")
lines(PredAged$mean, col="green")
EQM(MSEAnnTest, VARAGEDSMICTCHO$forecast$MSEAnnTrain$mean)
EQM(MSEAnnTest, PredAged$mean)
plot(PIBAnnTest, ylim=c(2000,2500))
lines(VARCOMPLET$forecast$PIBAnnTrain$mean, col = "red")
plot(SMICAnnTest, ylim=c(9,12.5))
lines(VARCOMPLET$forecast$SMICAnnTrain$mean, col = "red")
plot(TCHOAnnTest, ylim=c(8.5,11))
lines(VARCOMPLET$forecast$TCHOAnnTrain$mean, col = "red")
plot(AGEDAnnTest, ylim=c(199,300))
lines(VARCOMPLET$forecast$AGEDAnnTrain$mean, col = "red")

##Trimestriel
#1 Variable

#PIB
VARselect(cbind(MSETrimTrain, PIBTrimTrain), lag.max = 10, season=4)
VAR(cbind(MSETrimTrain, PIBTrimTrain), p=5, season=4, type="trend")
VARPIBTrim <- forecast(VAR(cbind(MSETrimTrain, PIBTrimTrain), p=5, season = 4))
plot(MSETrimTest, ylim=c(1.3e+9, 1.6e+9))
lines(VARPIBTrim$forecast$MSETrimTrain$mean, col = "red")
lines(PredPIBTCHO$mean, col="green")
EQM(MSETrimTest, VARPIBTrim$forecast$MSETrimTrain$mean)
EQM(MSETrimTest, PredPIBTCHO$mean)
plot(PIBTrimTest, ylim=c(525000,535000))
lines(VARPIBTrim$forecast$PIBTrimTrain$mean, col = "red")

#SMIC
VARselect(cbind(MSETrimTrain, SMICTrimTrain), lag.max = 10, season=4)
VAR(cbind(MSETrimTrain, SMICTrimTrain), p=5, season=4, type="trend")
VARSMICTrim <- forecast(VAR(cbind(MSETrimTrain, SMICTrimTrain), p=5, season = 4))
plot(MSETrimTest, ylim=c(1.3e+9, 1.6e+9))
lines(VARSMICTrim$forecast$MSETrimTrain$mean, col = "red")
lines(PredPIBTCHO$mean, col="green")
EQM(MSETrimTest, VARPIBTrim$forecast$MSETrimTrain$mean)
EQM(MSETrimTest, PredPIBTCHO$mean)
plot(SMICTrimTest, ylim=c(9.5,10))
lines(VARSMICTrim$forecast$SMICTrimTrain$mean, col = "red")

#TCHO
VARselect(cbind(MSETrimTrain, TCHOTrimTrain), lag.max = 10, season=4)
VAR(cbind(MSETrimTrain, TCHOTrimTrain), p=5, season=4, type="trend")
VARTCHOTrim <- forecast(VAR(cbind(MSETrimTrain, TCHOTrimTrain), p=5, season=4))
plot(MSETrimTest, ylim=c(1.3e+9, 1.6e+9))
lines(VARTCHOTrim$forecast$MSETrimTrain$mean, col = "red")
lines(PredPIBTCHO$mean, col="green")
EQM(MSETrimTest, VARPIBTrim$forecast$MSETrimTrain$mean)
EQM(MSETrimTest, PredPIBTCHO$mean)
plot(TCHOTrimTest, ylim=c(8.9,10))
lines(VARTCHOTrim$forecast$TCHOTrimTrain$mean, col = "red")

plot(MSETrimTest, main="Comparaison des modèles avec 1 variable", ylim=c(1.35e+9, 1.65e+9))
lines(VARPIBTrim$forecast$MSETrimTrain$mean, col="green")
lines(VARSMICTrim$forecast$MSETrimTrain$mean, col="red")
lines(VARTCHOTrim$forecast$MSETrimTrain$mean, col="gold")
legend('bottomright', legend = c('Série MSE', 'PIB', 'SMIC', 'Taux chômage'),
       col=c('black', 'green', 'red', 'gold'), lty=1, cex=0.8)

#2 Variables
#PIB & SMIC
VARselect(cbind(MSETrimTrain, PIBTrimTrain, SMICTrimTrain), lag.max = 10, season=4)
VAR(cbind(MSETrimTrain, PIBTrimTrain, SMICTrimTrain), p=5, season=4, type="trend")
VARPIBSMICTrim <- forecast(VAR(cbind(MSETrimTrain, PIBTrimTrain, SMICTrimTrain), p=5, season = 4))
plot(MSETrimTest, ylim=c(1.3e+9, 1.6e+9))
lines(VARPIBSMICTrim$forecast$MSETrimTrain$mean, col = "red")
lines(PredPIBTCHO$mean, col="green")
EQM(MSETrimTest, VARPIBSMICTrim$forecast$MSETrimTrain$mean)
EQM(MSETrimTest, PredPIBTCHO$mean)
plot(PIBTrimTest, ylim=c(525000,535000))
lines(VARPIBSMICTrim$forecast$PIBTrimTrain$mean, col = "red")
plot(SMICTrimTest, ylim=c(9.5,10))
lines(VARPIBSMICTrim$forecast$SMICTrimTrain$mean, col = "red")

#PIB & TCHO
VARselect(cbind(MSETrimTrain, PIBTrimTrain, TCHOTrimTrain), lag.max = 10, season=4)
VAR(cbind(MSETrimTrain, PIBTrimTrain, TCHOTrimTrain), p=5, season=4, type="trend")
VARPIBTCHOTrim <- forecast(VAR(cbind(MSETrimTrain, PIBTrimTrain, TCHOTrimTrain), p=5, season = 4))
plot(MSETrimTest, ylim=c(1.3e+9, 1.6e+9))
lines(VARPIBTCHOTrim$forecast$MSETrimTrain$mean, col = "red")
lines(PredPIBTCHO$mean, col="green")
EQM(MSETrimTest, VARPIBTCHOTrim$forecast$MSETrimTrain$mean)
EQM(MSETrimTest, PredPIBTCHO$mean)
plot(PIBTrimTest, ylim=c(525000,535000))
lines(VARPIBTCHOTrim$forecast$PIBTrimTrain$mean, col = "red")
plot(SMICTrimTest, ylim=c(9.5,10))
lines(VARPIBTCHOTrim$forecast$SMICTrimTrain$mean, col = "red")

#SMIC & TCHO
VARselect(cbind(MSETrimTrain, SMICTrimTrain, TCHOTrimTrain), lag.max = 10, season=4)
VAR(cbind(MSETrimTrain, SMICTrimTrain, TCHOTrimTrain), p=5, season=4, type="trend")
VARSMICTCHOTrim <- forecast(VAR(cbind(MSETrimTrain, SMICTrimTrain, TCHOTrimTrain), p=5, season = 4))
plot(MSETrimTest, ylim=c(1.3e+9, 1.6e+9))
lines(VARSMICTCHOTrim$forecast$MSETrimTrain$mean, col = "red")
lines(PredPIBTCHO$mean, col="green")
EQM(MSETrimTest, VARSMICTCHOTrim$forecast$MSETrimTrain$mean)
EQM(MSETrimTest, PredPIBTCHO$mean)
plot(SMICTrimTest, ylim=c(9.5,10))
lines(VARSMICTCHOTrim$forecast$SMICTrimTrain$mean, col = "red")
plot(TCHOTrimTest, ylim=c(8.8,10))
lines(VARSMICTCHOTrim$forecast$TCHOTrimTrain$mean, col = "red")

plot(MSETrimTest, main="Comparaison des modèles avec 1 variable", ylim=c(1.35e+9, 1.65e+9))
lines(VARPIBSMICTrim$forecast$MSETrimTrain$mean, col="green")
lines(VARPIBTCHOTrim$forecast$MSETrimTrain$mean, col="red")
lines(VARSMICTCHOTrim$forecast$MSETrimTrain$mean, col="gold")
legend('bottomright', legend = c('Série MSE', 'PIB', 'SMIC', 'Taux chômage'),
       col=c('black', 'green', 'red', 'gold'), lty=1, cex=0.8)

#3 Variables
VARselect(cbind(MSETrimTrain, SMICTrimTrain, TCHOTrimTrain, PIBTrimTrain), lag.max = 19, season=4)
VAR(cbind(MSETrimTrain, SMICTrimTrain, TCHOTrimTrain, PIBTrimTrain), p=19, season=4, type="trend")
VARPIBSMICTCHOTrim <- forecast(VAR(cbind(MSETrimTrain, SMICTrimTrain, TCHOTrimTrain, PIBTrimTrain), p=19, season = 4))
plot(MSETrimTest, ylim=c(1.3e+9, 1.7e+9))
lines(VARPIBSMICTCHOTrim$forecast$MSETrimTrain$mean, col = "red")
lines(PredPIBTCHO$mean, col="green")
EQM(MSETrimTest, VARPIBSMICTCHOTrim$forecast$MSETrimTrain$mean)
EQM(MSETrimTest, PredPIBTCHO$mean)
plot(SMICTrimTest, ylim=c(9.5,10))
lines(VARPIBSMICTCHOTrim$forecast$SMICTrimTrain$mean, col = "red")
plot(TCHOTrimTest, ylim=c(8.8,14))
lines(VARPIBSMICTCHOTrim$forecast$TCHOTrimTrain$mean, col = "red")
plot(PIBTrimTest, ylim=c(500000,550000))
lines(VARPIBSMICTCHOTrim$forecast$PIBTrimTrain$mean, col = "red")
